import '../sdk/study_client.dart';

final starterStudyPayloads = <StartSessionEntryPayload>[
  _entry(
    sourceId: 'entry-adapt',
    word: 'adapt',
    partOfSpeech: 'v.',
    phoneticUs: '/adapt/',
    meaningCn: '适应',
    meaningEn: 'adjust to change',
    exampleSentence: 'We must adapt to change.',
    exampleTranslation: '我们必须适应变化。',
  ),
  _entry(
    sourceId: 'entry-approach',
    word: 'approach',
    partOfSpeech: 'n.',
    phoneticUs: '/approach/',
    meaningCn: '方法',
    meaningEn: 'a way of dealing with something',
    exampleSentence: 'We need a practical approach.',
    exampleTranslation: '我们需要一种务实的方法。',
  ),
  _entry(
    sourceId: 'entry-remote',
    word: 'remote',
    partOfSpeech: 'adj.',
    phoneticUs: '/remote/',
    meaningCn: '偏远的',
    meaningEn: 'far away from cities',
    exampleSentence: 'They worked in a remote village.',
    exampleTranslation: '他们在一个偏远村庄工作。',
  ),
  _entry(
    sourceId: 'entry-salary',
    word: 'salary',
    partOfSpeech: 'n.',
    phoneticUs: '/salary/',
    meaningCn: '薪水',
    meaningEn: 'fixed monthly pay',
    exampleSentence: 'Her salary increased this year.',
    exampleTranslation: '她今年的薪水上涨了。',
  ),
  _entry(
    sourceId: 'entry-enhance',
    word: 'enhance',
    partOfSpeech: 'v.',
    phoneticUs: '/enhance/',
    meaningCn: '提升',
    meaningEn: 'improve something',
    exampleSentence: 'These examples enhance understanding.',
    exampleTranslation: '这些例子能提升理解。',
  ),
];

final fallbackDistractorPayloads = <StartSessionEntryPayload>[
  _entry(
    sourceId: 'verb-clarify',
    word: 'clarify',
    partOfSpeech: 'v.',
    phoneticUs: '/clarify/',
    meaningCn: '澄清',
    meaningEn: 'make clear',
  ),
  _entry(
    sourceId: 'verb-retain',
    word: 'retain',
    partOfSpeech: 'v.',
    phoneticUs: '/retain/',
    meaningCn: '保留',
    meaningEn: 'keep',
  ),
  _entry(
    sourceId: 'verb-modify',
    word: 'modify',
    partOfSpeech: 'v.',
    phoneticUs: '/modify/',
    meaningCn: '修改',
    meaningEn: 'change slightly',
  ),
  _entry(
    sourceId: 'verb-govern',
    word: 'govern',
    partOfSpeech: 'v.',
    phoneticUs: '/govern/',
    meaningCn: '治理',
    meaningEn: 'rule or control',
  ),
  _entry(
    sourceId: 'verb-analyse',
    word: 'analyse',
    partOfSpeech: 'v.',
    phoneticUs: '/analyse/',
    meaningCn: '分析',
    meaningEn: 'examine carefully',
  ),
  _entry(
    sourceId: 'verb-discourage',
    word: 'discourage',
    partOfSpeech: 'v.',
    phoneticUs: '/discourage/',
    meaningCn: '使气馁',
    meaningEn: 'make less confident',
  ),
  _entry(
    sourceId: 'verb-resemble',
    word: 'resemble',
    partOfSpeech: 'v.',
    phoneticUs: '/resemble/',
    meaningCn: '像',
    meaningEn: 'be similar to',
  ),
  _entry(
    sourceId: 'verb-cancel',
    word: 'cancel',
    partOfSpeech: 'v.',
    phoneticUs: '/cancel/',
    meaningCn: '取消',
    meaningEn: 'decide not to continue',
  ),
  _entry(
    sourceId: 'verb-restore',
    word: 'restore',
    partOfSpeech: 'v.',
    phoneticUs: '/restore/',
    meaningCn: '恢复',
    meaningEn: 'bring back',
  ),
  _entry(
    sourceId: 'noun-method',
    word: 'method',
    partOfSpeech: 'n.',
    phoneticUs: '/method/',
    meaningCn: '方法',
    meaningEn: 'a way of doing something',
  ),
  _entry(
    sourceId: 'noun-convention',
    word: 'convention',
    partOfSpeech: 'n.',
    phoneticUs: '/convention/',
    meaningCn: '惯例',
    meaningEn: 'usual way of behaving',
  ),
  _entry(
    sourceId: 'noun-disease',
    word: 'disease',
    partOfSpeech: 'n.',
    phoneticUs: '/disease/',
    meaningCn: '疾病',
    meaningEn: 'illness',
  ),
  _entry(
    sourceId: 'noun-pollution',
    word: 'pollution',
    partOfSpeech: 'n.',
    phoneticUs: '/pollution/',
    meaningCn: '污染',
    meaningEn: 'environmental contamination',
  ),
  _entry(
    sourceId: 'noun-center',
    word: 'center',
    partOfSpeech: 'n.',
    phoneticUs: '/center/',
    meaningCn: '中心',
    meaningEn: 'middle point',
  ),
  _entry(
    sourceId: 'noun-burden',
    word: 'burden',
    partOfSpeech: 'n.',
    phoneticUs: '/burden/',
    meaningCn: '负担',
    meaningEn: 'heavy responsibility',
  ),
  _entry(
    sourceId: 'noun-policy',
    word: 'policy',
    partOfSpeech: 'n.',
    phoneticUs: '/policy/',
    meaningCn: '政策',
    meaningEn: 'official plan',
  ),
  _entry(
    sourceId: 'adj-numerous',
    word: 'numerous',
    partOfSpeech: 'adj.',
    phoneticUs: '/numerous/',
    meaningCn: '许多的',
    meaningEn: 'many',
  ),
  _entry(
    sourceId: 'adj-explosive',
    word: 'explosive',
    partOfSpeech: 'adj.',
    phoneticUs: '/explosive/',
    meaningCn: '爆炸性的',
    meaningEn: 'able to explode',
  ),
  _entry(
    sourceId: 'adj-flexible',
    word: 'flexible',
    partOfSpeech: 'adj.',
    phoneticUs: '/flexible/',
    meaningCn: '灵活的',
    meaningEn: 'able to change easily',
  ),
  _entry(
    sourceId: 'adj-suspicious',
    word: 'suspicious',
    partOfSpeech: 'adj.',
    phoneticUs: '/suspicious/',
    meaningCn: '可疑的',
    meaningEn: 'causing doubt',
  ),
  _entry(
    sourceId: 'adj-conventional',
    word: 'conventional',
    partOfSpeech: 'adj.',
    phoneticUs: '/conventional/',
    meaningCn: '传统的',
    meaningEn: 'following accepted practice',
  ),
  _entry(
    sourceId: 'adj-precise',
    word: 'precise',
    partOfSpeech: 'adj.',
    phoneticUs: '/precise/',
    meaningCn: '精确的',
    meaningEn: 'exact and accurate',
  ),
];

final rootAffixFallbackPayloads = <StartSessionEntryPayload>[
  _root(
    sourceId: 'root-hyper',
    form: 'hyper-',
    meaningCn: '高、过度、超过',
    exampleWords: 'hypertension, hypercapnia, hyperactive',
    exampleGlosses: '高血压, 二氧化碳过多, 过度活跃',
  ),
  _root(
    sourceId: 'root-hypo',
    form: 'hypo-',
    meaningCn: '低、不足、在下',
    exampleWords: 'hypoxia, hypoglycemia, hypothyroid',
    exampleGlosses: '缺氧, 低血糖, 甲状腺功能低下',
  ),
  _root(
    sourceId: 'root-broncho',
    form: 'broncho-',
    meaningCn: '支气管',
    exampleWords: 'bronchitis, bronchoscopy, bronchodilator',
    exampleGlosses: '支气管炎, 支气管镜检查, 支气管扩张剂',
  ),
  _root(
    sourceId: 'root-cardio',
    form: 'cardio-',
    meaningCn: '心脏',
    exampleWords: 'cardiology, cardiovascular, cardiomyopathy',
    exampleGlosses: '心脏病学, 心血管的, 心肌病',
  ),
  _root(
    sourceId: 'root-hepato',
    form: 'hepato-',
    meaningCn: '肝脏',
    exampleWords: 'hepatology, hepatocyte, hepatomegaly',
    exampleGlosses: '肝脏病学, 肝细胞, 肝肿大',
  ),
  _root(
    sourceId: 'root-neuro',
    form: 'neuro-',
    meaningCn: '神经',
    exampleWords: 'neurology, neuropathy, neurotoxin',
    exampleGlosses: '神经病学, 神经病变, 神经毒素',
  ),
  _root(
    sourceId: 'suffix-itis',
    form: '-itis',
    meaningCn: '炎症',
    exampleWords: 'bronchitis, gastritis, tonsillitis',
    exampleGlosses: '支气管炎, 胃炎, 扁桃体炎',
  ),
  _root(
    sourceId: 'suffix-ology',
    form: '-ology',
    meaningCn: '学科、研究',
    exampleWords: 'cardiology, pathology, histology',
    exampleGlosses: '心脏病学, 病理学, 组织学',
  ),
  _root(
    sourceId: 'suffix-scopy',
    form: '-scopy',
    meaningCn: '镜检、观察',
    exampleWords: 'bronchoscopy, endoscopy, microscopy',
    exampleGlosses: '支气管镜检查, 内窥镜检查, 显微镜检查',
  ),
  _root(
    sourceId: 'suffix-emia',
    form: '-emia',
    meaningCn: '血液状态',
    exampleWords: 'anemia, bacteremia, hyperglycemia',
    exampleGlosses: '贫血, 菌血症, 高血糖',
  ),
];

StartSessionEntryPayload _entry({
  required String sourceId,
  required String word,
  required String partOfSpeech,
  required String phoneticUs,
  required String meaningCn,
  required String meaningEn,
  String? exampleSentence,
  String? exampleTranslation,
}) =>
    StartSessionEntryPayload(
  sourceId: sourceId,
  word: word,
  partOfSpeech: partOfSpeech,
  phoneticUs: phoneticUs,
  meanings: <String>[meaningCn],
  meaningDetails: <Map<String, dynamic>>[
    <String, dynamic>{
      'pos': partOfSpeech,
      'meaningCn': meaningCn,
      'meaningEn': meaningEn,
    },
  ],
  exampleSentence: exampleSentence,
  exampleTranslation: exampleTranslation,
    );

StartSessionEntryPayload _root({
  required String sourceId,
  required String form,
  required String meaningCn,
  required String exampleWords,
  required String exampleGlosses,
}) =>
    StartSessionEntryPayload(
  sourceId: sourceId,
  word: form,
  meanings: <String>[meaningCn],
  meaningDetails: <Map<String, dynamic>>[
    <String, dynamic>{
      'pos': 'root',
      'meaningCn': meaningCn,
      'meaningEn': '',
    },
  ],
  exampleSentence: exampleWords,
  exampleTranslation: exampleGlosses,
    );
